name: v1 branch CI

on:
  push:
    branches: [ "v1" ]  # main 브랜치에 푸시될 때만 동작

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # (1) 소스코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # (2) application.yml 생성
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.TEST_APP_YML }}" > src/main/resources/application.yml
          
      # (2)-1 Logback config 주입    
      - name: Decode logback-spring.xml
        run: |
          echo "${{ secrets.LOGBACK_CONFIG }}" | base64 --decode > src/main/resources/logback-spring.xml
          
      # (3) JDK 설정
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # (4) Gradle 빌드
      - name: Build (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          ls -alh build/libs

      # (5) AWS 자격증명 세팅
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # (6) 빌드 산출물 (JAR) S3 업로드
      - name: Upload jar to S3
        run: |
          aws s3 cp \
            build/libs/eventer-0.0.1-SNAPSHOT.jar \
            s3://${{ secrets.BUCKET_NAME }}/backend/eventer-0.0.1-SNAPSHOT.jar

      # # (7) Code Deploy 실행
      # - name: Trigger CodeDeploy Deployment
      #   uses: aws-actions/aws-cli-action@v4
      #   with:
      #     command: deploy create-deployment
      #     args: >
      #       --application-name waba-backend-cd
      #       --deployment-group-name MyDeploymentGroup
      #       --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=jar,key=backend/eventer-0.0.1-SNAPSHOT.jar


        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
